### ISSUE TITLE
[BUG] - lange aaneensluitende tekst in titel of metadata wordt niet correct gerenderd  

### ISSUE THREAD

**Issue by Rubenth** [milieuinfo/webcomponent-vl-ui-document#11]
**Omschrijf het probleem**
Wanneer title of metadata te lange aaneensluitende tekst bevat, wordt deze niet correct gewrapped. De breedte wordt dynamisch gezet waardoor een deel van de tekst verdwijnt. 

**Hoe te reproduceren**

- Naar de demo pagina gaan https://webcomponenten.omgeving.vlaanderen.be/demo/vl-document.html
- inspect -> title of metadata tekst aanpassen naar "ditiseenhelelangetekstdiegeenspatiesbevatendaardoordusnietdeftiggetoondwordtophetscherm"

**Gewenst gedrag**
Dat alle tekst getoond wordt, ongeacht of het te lang is of niet. 

**Screenshots**
<img width="1113" alt="Screenshot 2021-03-04 at 16 55 16" src="https://user-images.githubusercontent.com/8820456/109991213-686c3900-7d0a-11eb-8882-a8218620ff04.png">

**Omgeving (gelieve aan te vullen):**
 - Browser chrome
 - Versie component 1.0.2

**Comment by kevcraey** [comment]
non issue
